# Generated by Django 5.2.3 on 2025-06-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_delete_listing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранный', 'verbose_name_plural': 'Избранные'},
        ),
    ]
